FROM openjdk:17-oracle

ENV CUSTOMER_DATASOURCE_URL ''
ENV CUSTOMER_DATASOURCE_USER ''
ENV CUSTOMER_DATASOURCE_PASSWORD ''

ARG JAR_FILE=target/customer.jar
ADD ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","app.jar"]